background:
- 255
- 219
- 187
red:
  - 255
  - 0
  - 0
green:
  - 0
  - 255
  - 0
blue:
  - 0
  - 0
  - 255
pink:
  - 255
  - 0
  - 155
white:
  - 255
  - 255
  - 255
black:
  - 0
  - 0
  - 0
yellow:
  - 255
  - 255
  - 0
cyan:
  - 0
  - 255
  - 255
magenta:
  - 255
  - 0
  - 255
orange:
  - 255
  - 165
  - 0
purple:
  - 128
  - 0
  - 128
brown:
  - 139
  - 69
  - 19
gray:
  - 128
  - 128
  - 128
light_gray:
  - 211
  - 211
  - 211
dark_gray:
  - 64
  - 64
  - 64
navy:
  - 0
  - 0
  - 128
teal:
  - 0
  - 128
  - 128
lime:
  - 50
  - 205
  - 50
gold:
  - 255
  - 215
  - 0
beige:
  - 245
  - 245
  - 220
coral:
  - 255
  - 127
  - 80
turquoise:
  - 64
  - 224
  - 208
violet:
  - 238
  - 130
  - 238
indigo:
  - 75
  - 0
  - 130
