@startuml SimuladorBasicoGeracaoTrajetorias

title "TCC EAUTO FURG 2025 - Aprendizado Social entre Humanos e Agentes Artificiais - Experimento Humanos"

' Definição de estilo
skinparam ParticipantPadding 30
skinparam MaxMessageSize 180

autonumber

participant Usuário as User
participant "Internet" as IT
participant "Outros Players (humanos e LLMs)" as Players
participant "Sala de Espera" as WR
participant "Grupo Ativo em Jogo" as PActive
participant "Jogo" as Game
participant "Encerrado" as DISM

== Download e Configuração ==

User -> IT: Download do arquivo .exe
IT --> User: Arquivo baixado com sucesso
User -> User: Executa o jogo e configura o ambiente

== Início do Jogo ==

User -> WR: Entra na sala de espera
WR --> User: Confirmação de entrada no lobby

Players -> WR: Outros jogadores entram na sala de espera

== Dinâmica do Jogo ==

WR -> PActive: 4 jogadores entram no jogo
Game <- PActive: Inicia o Jogo 
Game --> PActive: Tela é exibida para os jogadores

group Troca de jogadores 
    group Ciclos de fases (3 rodadas)
        PActive -> Game: Tentatam descobrir o objetivo
        Game --> PActive: Feedback baseado no score
        Game -> PActive: Objetivo cumprido com sucesso
    end

    PActive -> DISM: Um jogador do grupo é dispensado
    WR -> PActive: Novo Jogador entra na partida
end

@enduml
